server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false

debug: false

#DataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zftools?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwerty

#Mybatis
mybatis:
  config-location: mybatis-config.xml
  mapper-locations: /mapper/**.xml
  entity_package: com.ziroom.zftools.entity
